name: Deploy to Dev and QA

on:
  push:
    branches:
      - master

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build Docker Image
        run: docker build -t imagedeployment:latest .
