name: Azure Container Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://kubecontainer45.azurecr.io/
          username: ${{ secrets.REGISTRY_USERNAME  }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kubecontainer45.azurecr.io/sample:v${{ github.sha }}
          file: ./Dockerfile

  deployDev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'Dev'
      url: ${{ steps.deploy-to-webapp-dev.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp-dev
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dockerimagetest'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV_SERVER }}
          images: 'kubecontainer45.azurecr.io/sample:v${{ github.sha }}'

  deployQA:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: deployDev
    environment:
      name: 'QA'
      url: ${{ steps.deploy-to-webapp-qa.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp-qa
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dockerimagetestqa'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_QA_SERVER }}
          images: 'kubecontainer45.azurecr.io/sample:v${{ github.sha }}'

  deployProd:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: deployQA
    environment:
      name: 'PROD'
      url: ${{ steps.deploy-to-webapp-prod.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp-prod
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dockerimageprod'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD_SERVER }}
          images: 'kubecontainer45.azurecr.io/sample:v${{ github.sha }}'
