name: Azure Container Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker Image
        run: docker build -t imagedeployment:latest .

      - name: Deploy to Azure Web App (Dev)
        uses: azure/webapps-deploy@v2
        with:
          app-name: deploy-to-webapp-dev
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV_SERVER }}
          images: 'imagedeployment:latest'   
        
