name: Deploy to Dev and QA

on:
  push:
    branches:
      - main

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build Docker Image
        run: docker build -t imagedeployment:latest .

     
      - name: Deploy to Azure Web App (Dev)
        uses: azure/webapps-deploy@v2
        with:
          app-name: deploy-to-webapp-dev
          images: 'imagedeployment:latest'
